2023/05/29 16:01:59 [error] 394#394: *1 SSL_do_handshake() failed (SSL: error:0A00010B:SSL routines::wrong version number) while SSL handshaking to upstream, client: 172.31.0.1, server: _, request: "GET /graphql HTTP/2.0", upstream: "https://172.31.0.3:4000/graphql", host: "simontp.duckdns.org"
2023/05/29 16:02:26 [error] 394#394: *1 SSL_do_handshake() failed (SSL: error:0A00010B:SSL routines::wrong version number) while SSL handshaking to upstream, client: 172.31.0.1, server: _, request: "GET /graphql HTTP/2.0", upstream: "https://172.31.0.3:4000/graphql", host: "simontp.duckdns.org"
2023/05/29 16:04:46 [error] 392#392: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: _, request: "GET /graphql HTTP/2.0", upstream: "https://127.0.0.1:4000/graphql", host: "simontp.duckdns.org"
2023/05/29 16:04:47 [error] 392#392: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: _, request: "GET /graphql HTTP/2.0", upstream: "https://127.0.0.1:4000/graphql", host: "simontp.duckdns.org"
2023/05/29 16:04:47 [error] 392#392: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: _, request: "GET /graphql HTTP/2.0", upstream: "https://127.0.0.1:4000/graphql", host: "simontp.duckdns.org"
2023/05/29 16:04:48 [error] 392#392: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: _, request: "GET /graphql HTTP/2.0", upstream: "https://127.0.0.1:4000/graphql", host: "simontp.duckdns.org"
2023/05/29 16:04:48 [error] 392#392: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: _, request: "GET /graphql HTTP/2.0", upstream: "https://127.0.0.1:4000/graphql", host: "simontp.duckdns.org"
2023/05/29 16:04:49 [error] 392#392: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: _, request: "GET /graphql HTTP/2.0", upstream: "https://127.0.0.1:4000/graphql", host: "simontp.duckdns.org"
2023/05/29 16:04:49 [error] 392#392: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: _, request: "GET /graphql HTTP/2.0", upstream: "https://127.0.0.1:4000/graphql", host: "simontp.duckdns.org"
2023/05/29 16:04:49 [error] 392#392: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: _, request: "GET /graphql HTTP/2.0", upstream: "https://127.0.0.1:4000/graphql", host: "simontp.duckdns.org"
2023/05/29 16:04:49 [error] 392#392: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: _, request: "GET /graphql HTTP/2.0", upstream: "https://127.0.0.1:4000/graphql", host: "simontp.duckdns.org"
2023/05/29 16:04:49 [error] 392#392: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: _, request: "GET /graphql HTTP/2.0", upstream: "https://127.0.0.1:4000/graphql", host: "simontp.duckdns.org"
2023/05/29 16:04:50 [error] 392#392: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: _, request: "GET /graphql HTTP/2.0", upstream: "https://127.0.0.1:4000/graphql", host: "simontp.duckdns.org"
2023/05/29 16:04:50 [error] 392#392: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: _, request: "GET /graphql HTTP/2.0", upstream: "https://127.0.0.1:4000/graphql", host: "simontp.duckdns.org"
2023/05/29 16:09:20 [error] 395#395: *1 ldap-auth could not be resolved (3: Host not found), client: 192.168.0.1, server: _, request: "GET / HTTP/2.0", subrequest: "/auth", host: "simontp.duckdns.org"
2023/05/29 16:09:20 [error] 395#395: *1 auth request unexpected status: 502 while sending to client, client: 192.168.0.1, server: _, request: "GET / HTTP/2.0", host: "simontp.duckdns.org"
2023/05/29 16:09:21 [error] 395#395: *1 ldap-auth could not be resolved (3: Host not found), client: 192.168.0.1, server: _, request: "GET / HTTP/2.0", subrequest: "/auth", host: "simontp.duckdns.org"
2023/05/29 16:09:21 [error] 395#395: *1 auth request unexpected status: 502 while sending to client, client: 192.168.0.1, server: _, request: "GET / HTTP/2.0", host: "simontp.duckdns.org"
